# Configuration for the HomeNetworkService.

spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:h2:file:D:\Workspace\Playground\homeNetwork\src\main\resources\h2.db
    driverClassName: org.h2.Driver
    username: Lucky
    password: Lorenzo

  cache:
    jcache:
      config: classpath:ehcache.xml

homenetwork:
  speedtest:
    download:
      url: "http://ipv4.ikoula.testdebit.info/10M.iso"
      socketTimeout: 5000

    upload:
      url: "http://ipv4.ikoula.testdebit.info/"
      fileSize: 10000000
      socketTimeout: 5000