# Configuration for the HomeNetworkService.

spring:
  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/homenetwork
    username: drauschke
    password: Fightthepower

  cache:
    jcache:
      config: classpath:ehcache.xml

server:
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: password
    key-store-type: pkcs12
    key-alias: homenetworkcertificate
    key-password: password
  port: 8443

homenetwork:
  speedtest:
    download:
      # Defines the url that is used to specify a download resource.
      url: "http://ipv4.ikoula.testdebit.info/10M.iso"
      # Defines the socket timeout in milliseconds for the download test.
      socketTimeout: 5000

    upload:
      # Defines the url that is used to specify an upload endoint.
      url: "http://ipv4.ikoula.testdebit.info/"
      # Defines the size of the file that shall be uploaded in bytes
      fileSize: 10000000
      # Defines the socket timeout in milliseconds for the upload test.
      socketTimeout: 5000