# Configuration for the HomeNetworkService.

spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

    hibernate:
      ddl-auto: update

  datasource:
    #   Used for H2:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:

    #    Used for MariaDB:
    #    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/homenetwork
    #    username: drauschke
    #    password: Fightthepower

  cache:
    jcache:
      config: classpath:ehcache.xml

homenetwork:
  speedtest:
    download:
      url: "http://ipv4.ikoula.testdebit.info/10M.iso"
      socketTimeout: 5000

    upload:
      url: "http://ipv4.ikoula.testdebit.info/"
      fileSize: 10000000
      socketTimeout: 5000